dist: trusty
language: python

python:
  - "2.7"
# command to install dependencies

install:
  - pip install -r requirements.txt

before_script:
  - sudo apt-get update
  - sudo apt-get install firefox
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - tar -zxvf geckodriver-v0.15.0-linux64.tar.gz
  - sudo chmod u+x geckodriver
  - sudo mv geckodriver /usr/bin/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - uname -a

# command to run tests
script: cd frontend_tests; export BROWSER=Firefox; pytest
