language: python

python:
  - "2.7"
# command to install dependencies

install:
  - pip install -r requirements.txt

before_script:
  - sudo apt-get update
  - wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb
  - sudo dpkg -i google-chrome-stable_current_i386.deb
  - sudo apt-get -f install
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - uname -a

# command to run tests
script: cd frontend_tests; pytest
