language: python

python:
  - "2.7"
# command to install dependencies

install:
  - pip install -r requirements.txt

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - uname -a

# command to run tests
script: cd frontend_tests; pytest
